### ISSUE TITLE
SecureHoldAuton violates Java and WPILib practices

### ISSUE THREAD

**Issue by jrr6** [Roobotics-FRC/RooBot2018#8]
Instead of using an awkward chaining structure, `SecureHoldAuton` should be turned into a superclass of auton commands that need to secure a hold and should expose a method like `secureHold()` to its subclasses.

**Comment by Samasaur1** [comment]
I disagree. The entire point of writing `SecureHoldAuton` was to have a way to secure the hold on the cube before doing some other basic auton. This should not require any change to the auton itself. We want those to be a simple as possible so that we can chain them together into command groups. Speaking of command groups, they also won't ever use `SecureHoldAuton`, as they can use `RetainCubeAuton` themselves.

Overall, I think `SecureHoldAuton` should be kept as simple as possible, and I believe this is the way to do so.

**Comment by jrr6** [comment]
Yes, but it is still a hack that contravenes the very nature of the command-based architecture. Backlogging for further review (i.e., Alex).

**Comment by jrr6** [comment]
I somehow missed the part where you said you would only use it for Commands and not CommandGroups. In that case, this looks good. Closing…

**Comment by thefangbear** [comment]
To be honest I have to agree with Joseph's previous comment. 
IMO the design principle of command groups is so that the caller always keeps track of the action and subsequent actions are not exposed to subcommands. Although it seems like a minor issue for now.

The correct pattern should be to create a series of "subcommands" and a new master-command that chains them together. (without further context I won't comment more)

This is analogous to how you don't want nested callbacks in networking code, albeit most people do so.

**Comment by thefangbear** [comment]
And really it is wpilib people who needs to redesign their semantics. `addSequential` and `addParallel` are insufficient for scheduling command because they do not expose functionalities to handle chained dependencies. Ideally the semantics should be more similar to promises.

If we have time (I suggest ) our best approach is to write something that serves as a middle layer between us and them that could handle the proper semantics. I've seen this before, and it requires only a little effort
